### ISSUE TITLE
Fail to download Datasets

### ISSUE THREAD

**Issue by flyflyly** [andreschreiber/ROAR#1]
The link you provided failed to access and the dataset could not be downloaded. Can you provide another way to download the dataset?

**Comment by andreschreiber** [comment]
Hi, thank you for trying to download the dataset!
I just tried using the Box links on the README, and they seemed to be publicly accessible and I did not encounter any issues.
Would you be able to detail how the access is failing (i.e., is it not letting you access Box, is the download failing when you click download in Box, etc.)?

**Comment by flyflyly** [comment]
Thanks for your reply! I try to download the Box links on another computer, which gets success. I rechecked and found that the VPN could not be used when downloading the dataset on the Box website.

**Comment by andreschreiber** [comment]
Awesome! Happy to hear it works without the VPN!
